version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    env_file:
      - env.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - av
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    volumes:
      - /mnt/c/redis-data:/redis-data

  av:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clam:/var/lib/clamav

volumes:
  clam:

networks:
  outpost_network:
    external: true
